name: turtogatchi
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  cron: ^0.3.1
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.1.0
  url_launcher: ^6.0.12
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  lottie: ^3.1.2
  provider: ^6.0.1
  assets_audio_player: ^3.0.0
  cloud_firestore: ^5.0.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  fonts:
    - family: MarioOutlined
      fonts:
        - asset: assets/fonts/TypefaceMarioWorldPixelOutlineRegular-MVzKp.ttf
          weight: 400
    - family: MarioRegular
      fonts:
        - asset: assets/fonts/TypefaceMarioWorldPixelFilledRegular-rgVMx.ttf
          weight: 400

  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/audio/
    - assets/images/
    - assets/images/hunger/
    - assets/images/local_img/
    - assets/images/turtle/
    - assets/images/buttons/
    - assets/images/home/
    - assets/images/splash/
    - assets/images/accessories/
    - assets/images/gachapage/
